-   id: consistent-eslint-dependencies
    name: Keep ESLint dependencies consistent in hooks
    description: Ensure that the ESLint dependencies in the pre-commit hooks are consistent with the one used elsewhere in the repository
    language: node
    entry: dependency-consistency
    pass_filenames: false
    stages:
        - commit
        - manual
        - push
    files: ^(.pre-commit-config.yaml|.*/(yarn.lock|package-lock.json))$
